directories:
  output: dist-electron
  buildResources: build
appId: Pixel.Digital.Inventario
productName: Inventario
files:
  - filter:
      - main.js
      - frontend/dist/**/*
      - icono-moto-electron.ico
win:
  icon: icono-moto-electron.ico
  target: nsis
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
electronVersion: 29.4.6
